#!/bin/bash -ex
# Finish up - executed after apply-overlay

# Change ownership of KT folder (and contents)
chown www-data -R /usr/share/knowledgetree-ce
chgrp www-data -R /usr/share/knowledgetree-ce


# Enable ssl apche module
#a2enmod ssl

# Enable knowledgetree on https 
cd /etc/apache2/sites-enabled/
ln -s /etc/apache2/sites-available/default-ssl default-ssl

#apache2ctl restart

#Stop services
service mysql stop
service apache2 stop
service postfix stop

#Clean apt cache
apt-get clean

# tell the world what we've done!
echo 'TKL KnowledgeTree appliance patch applied!' >> /etc/issue
