#!/bin/bash -ex
# Finish up - executed after apply-overlay

# Change ownership of KT folder (and contents)
chown www-data -R /usr/share/knowledgetree-ce
chgrp www-data -R /usr/share/knowledgetree-ce

#Stop services
service mysql stop
service apache2 stop
service postfix stop

#Clean apt cache
apt-get clean

#End
