#!/bin/bash -ex
# KnowledgeTree TKLPatch by JedMeister v0.11
# The patch has had a fairly major rejig since v0.10

#The overlay also includes some security fixes - as described here:

# http://wiki.knowledgetree.org/Security_advisory:_URL_Manipulation
# http://wiki.knowledgetree.org/Security_advisory:_KnowledgeTree_login.php_Blind_SQL_Injection

# Source our custom functions
cwd=$(dirname $0)
source $cwd/functions

HOSTNAME=knowledgetree

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# Import KT & Zend apt repo keys
wget http://repos.knowledgetree.com/deb/knowledgetree/kt.key -O- | apt-key add -
wget http://repos.zend.com/zend.key -O- | apt-key add -

# Add Canonical 'partner' repo
echo "## Canonical's 'partner' repository." > /etc/apt/sources.list.d/canonicalpartner.list
echo "## This software is not part of Ubuntu, but is offered by Canonical and the" >> /etc/apt/sources.list.d/canonicalpartner.list
echo "## respective vendors as a service to Ubuntu users." >> /etc/apt/sources.list.d/canonicalpartner.list
echo >> /etc/apt/sources.list.d/canonicalpartner.list
echo "deb http://archive.canonical.com/ubuntu lucid partner" >> /etc/apt/sources.list.d/canonicalpartner.list
echo "# deb-src http://archive.canonical.com/ubuntu lucid partner" >> /etc/apt/sources.list.d/canonicalpartner.list

# Add KnowledgeTree repo
echo "#--Knowledge Tree Community Edition offical repo" > /etc/apt/sources.list.d/knowledgetree.list
echo >> /etc/apt/sources.list.d/knowledgetree.list
echo "deb http://repos.knowledgetree.com/deb/knowledgetree knowledgetree-ce main" >> /etc/apt/sources.list.d/knowledgetree.list

# Add Zend Server repo
echo "#--Zend Server repo (contains both free and non-free pkgs)" > /etc/apt/sources.list.d/zendserver.list
echo >> /etc/apt/sources.list.d/zendserver.list
echo "deb http://repos.zend.com/zend-server/deb server non-free" >> /etc/apt/sources.list.d/zendserver.list

# Install KTCE (KT Community Edition) and some other stuff
install knowledgetree-ce 

# Install some other stuff
install ssl-cert postfix webmin-postfix 

# Disable Zend UI (by default won't allow connections other than local anyway)
a2dissite zendserver_gui.conf
a2dissite default

# Remove config.ini from KT config folder and link to conf in /etc (to avoid confusion)
rm -f /usr/share/knowledgetree-ce/config/config.ini
ln -s /etc/knowledgetree-ce/config.ini /usr/share/knowledgetree-ce/config/config.ini

# Create link to KT webroot in default webroot (/var/www)
ln -s /usr/share/knowledgetree-ce /var/www/knowledgetree

# Create database - will need to go in post.conf - this is the backup plan...
mysqladmin -u root create dms
#mysql -u root dms < /tmp/ktce.sql

# Create KT default database users
mysql -u root dms < /usr/share/knowledgetree-ce/sql/mysql/install/user.sql

# Create database tables
mysql -u root dms < /usr/share/knowledgetree-ce/sql/mysql/install/structure.sql
mysql -u root dms < /usr/share/knowledgetree-ce/sql/mysql/install/data.sql

# Now overlay files
