#!/bin/bash -e
# Regen KnowledgeTree MySQL user random passwords

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF_FILE=/etc/knowledgetree-ce/config.ini
VALUE1="dbPass"
VALUE2="dbAdminPass"

cp $CONF_FILE $CONF_FILE.backup
REPLACE1=s/${VALUE1}.*/${VALUE1}" = "${PASSWORD}/
REPLACE2=s/${VALUE2}.*/${VALUE2}" = "${PASSWORD}/
sed -i "$REPLACE1" "$CONF_FILE"
sed -i "$REPLACE2" "$CONF_FILE"

$INITHOOKS_PATH/bin/mysqlconf.py --user=dms --pass="$PASSWORD"
$INITHOOKS_PATH/bin/mysqlconf.py --user=dmsadmin --pass="$PASSWORD"